# Generated by Django 5.2.7 on 2025-11-13 13:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('Habitation', [('CHAMBRE', 'Chambre'), ('APPART', 'Appartement')]), ('Commercial', [('BUREAU', 'Bureau'), ('MAGASIN', 'Magasin'), ('BOUTIQUE', 'Boutique')])], max_length=10, verbose_name='Type de bien')),
                ('addresse', models.TextField()),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_chambres', models.PositiveIntegerField()),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('MOB', 'Mobile Money'), ('ESP', 'Espèces'), ('VIR', 'Virement Bancaire'), ('DEP', "Dépôt d'espèces en banque")], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('AG', 'Agence Immobilière'), ('PR', 'Propriétaire')], max_length=2)),
                ('telephone', models.CharField(max_length=20)),
                ('addresse', models.TextField(blank=True)),
                ('photo_profil', models.ImageField(default='profile_pics/default_avatar.jpg', upload_to=gestion.models.user_profile_pic_path, verbose_name='Photo de profil')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Doit changer le mot de passe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'gestion_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=gestion.models.agence_logo_path, verbose_name="Logo de l'agence")),
                ('rccm', models.CharField(blank=True, max_length=100, verbose_name='Numéro RCCM')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='Numéro NIF')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('raison_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='gestion.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_unite', models.CharField(choices=[('Habitation', [('CHAMBRE', 'Chambre'), ('APPART', 'Appartement')]), ('Commercial', [('BUREAU', 'Bureau'), ('MAGASIN', 'Magasin'), ('BOUTIQUE', 'Boutique')])], max_length=10, verbose_name="Type d'unité")),
                ('identifiant', models.CharField(help_text='Ex: 101, A-02, RDC Gauche', max_length=50, verbose_name='Identifiant/Numéro')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_loyer', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_mise_en_location', models.DateField(blank=True, null=True)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='gestion.immeuble')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambres', to='gestion.locataire')),
            ],
            options={
                'unique_together': {('immeuble', 'type_unite', 'identifiant')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestion.chambre')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestion.locataire')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.moyenpaiement')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='Lien optionnel vers la ressource concernée', null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion.agence')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut_contrat', models.DateField()),
                ('duree_contrat', models.PositiveIntegerField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='gestion.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immeubles', to='gestion.proprietaire'),
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('ENT', "État des lieux d'entrée"), ('SOR', 'État des lieux de sortie')], max_length=3, verbose_name='Type de rapport')),
                ('date_etat', models.DateField(default=django.utils.timezone.now, verbose_name='Date du rapport')),
                ('description', models.TextField(verbose_name="Description générale de l'état (murs, sols, équipements, etc.)")),
                ('document_signe', models.FileField(blank=True, null=True, upload_to=gestion.models.etat_des_lieux_path, verbose_name='Document signé (PDF, Image)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='gestion.location')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_etat'],
                'unique_together': {('location', 'type_etat')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateField()),
                ('mois_couvert', models.CharField(max_length=20)),
                ('est_valide', models.BooleanField(default=False)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='preuves_paiement/', verbose_name='Preuve de Paiement')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.location')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.moyenpaiement')),
            ],
            options={
                'unique_together': {('location', 'mois_couvert')},
            },
        ),
    ]
