# Generated by Django 5.2.7 on 2025-11-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        # Opération manuelle pour corriger l'incohérence de nom de table.
        # On renomme l'ancienne table 'gestion_bien' vers le nom standard 'gestion_immeuble'.
        migrations.AlterModelTable(
            name='immeuble',
            table='gestion_immeuble',
        ),
    ]
