# Generated by Django 4.1.3 on 2025-07-21 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Appartement T3 - Centre-ville', max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agence', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_geres', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(limit_choices_to={'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
