# Generated by Django 4.1.3 on 2025-07-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='nombre_bien',
        ),
    ]
