# Generated by Django 5.2.7 on 2025-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_immeuble_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immeuble',
            options={'verbose_name': 'Immeuble', 'verbose_name_plural': 'Immeubles'},
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_unite',
            field=models.CharField(choices=[('CHAMBRE', 'Chambre'), ('APPART', 'Appartement'), ('BUREAU', 'Bureau'), ('MAGASIN', 'Magasin'), ('BOUTIQUE', 'Boutique')], max_length=10, verbose_name="Type d'unité"),
        ),
        migrations.AlterModelTable(
            name='immeuble',
            table=None,
        ),
    ]
