# Generated by Django 4.1.3 on 2025-07-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_proprietaire_nombre_bien'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bien',
        ),
    ]
