# Generated by Django 5.2.7 on 2025-11-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_immeuble_options_alter_chambre_type_unite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeuble',
            name='type_bien',
            field=models.CharField(choices=[('CHAMBRE', 'Chambre'), ('APPART', 'Appartement'), ('BUREAU', 'Bureau'), ('MAGASIN', 'Magasin'), ('BOUTIQUE', 'Boutique')], max_length=10, verbose_name='Type de bien'),
        ),
    ]
