# Generated by Django 4.1.3 on 2025-07-30 14:39

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_delete_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.user_profile_pic_path, verbose_name='Photo de profil'),
        ),
    ]
