# Generated by Django 4.1.3 on 2025-07-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('location', 'mois_couvert')},
        ),
    ]
