# Generated by Django 4.1.3 on 2025-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_paiement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='siret',
        ),
        migrations.AddField(
            model_name='agence',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro NIF'),
        ),
        migrations.AddField(
            model_name='agence',
            name='rccm',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro RCCM'),
        ),
    ]
