# Generated by Django 4.1.3 on 2025-08-01 21:38

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_agence_siret_agence_nif_agence_rccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.agence_logo_path, verbose_name="Logo de l'agence"),
        ),
    ]
