# Generated by Django 4.1.3 on 2025-08-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_agence_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('ENT', "État des lieux d'entrée"), ('SOR', 'État des lieux de sortie')], max_length=3, verbose_name='Type de rapport')),
                ('date_etat', models.DateField(default=django.utils.timezone.now, verbose_name='Date du rapport')),
                ('description', models.TextField(verbose_name="Description générale de l'état (murs, sols, équipements, etc.)")),
                ('document_signe', models.FileField(blank=True, null=True, upload_to=gestion.models.etat_des_lieux_path, verbose_name='Document signé (PDF, Image)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='gestion.location')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_etat'],
                'unique_together': {('location', 'type_etat')},
            },
        ),
    ]
