# Generated by Django 5.2.4 on 2025-08-05 12:15

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_etatdeslieux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(default='profile_pics/default_avatar.jpg', upload_to=gestion.models.user_profile_pic_path, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='designation',
            field=models.CharField(choices=[('MOB', 'Mobile Money'), ('ESP', 'Espèces'), ('VIR', 'Virement Bancaire'), ('DEPOT_ESPECES', "Dépôt d'espèces en banque")], max_length=50, unique=True),
        ),
    ]
