# Generated by Django 5.2.4 on 2025-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_customuser_photo_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='designation',
            field=models.CharField(choices=[('MOB', 'Mobile Money'), ('ESP', 'Espèces'), ('VIR', 'Virement Bancaire'), ('DEP', "Dépôt d'espèces en banque")], max_length=50, unique=True),
        ),
    ]
