# Generated by Django 5.2.4 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_moyenpaiement_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='preuve_paiement',
            field=models.FileField(blank=True, null=True, upload_to='preuves_paiement/', verbose_name='Preuve de Paiement'),
        ),
    ]
