# Generated by Django 4.1.3 on 2025-08-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_paiement_preuve_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='rccm',
        ),
    ]
