# Generated by Django 5.2.7 on 2025-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_agence_nif_remove_agence_rccm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addresse',
            field=models.TextField(blank=True),
        ),
    ]
