# Generated by Django 5.2.7 on 2025-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_customuser_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro NIF'),
        ),
        migrations.AddField(
            model_name='agence',
            name='rccm',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro RCCM'),
        ),
    ]
